# Default config:
# - https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml
# - rspec: https://github.com/rubocop-hq/rubocop-rspec/blob/master/config/default.yml

require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
    - !ruby/regexp /old_and_unused\.rb$/
Style/Documentation:
  Enabled: false
  Exclude:
    - '**/*.gemspec'
    - '**/*_spec.rb'
Layout/EndOfLine:
  EnforcedStyle: lf
RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - task
Style/StringLiterals:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
Style/FrozenStringLiteralComment:
  Enabled: false
