version: "3.9"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  snmp:
    image: rnwood/smtp4dev:v3
    ports:
      - "80:80"
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      # FIXME: Duplicate with Dockerfile. Still necessary?
      SECRET_KEY_BASE: Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw
      MONITOFEN_DB_HOST: db
      MONITOFEN_DB_USERNAME: postgres
      MONITOFEN_DB_PASSWORD: password
      MONITOFEN_DB_NAME: monitofen
      MONITOFEN_BOILER_BASE_URL: $BOILER_BASE_URL
      SMTP_USERNAME:
      SMTP_PASSWORD:
      SMTP_DOMAIN: monitofen.com
      SMTP_HOST: snmp
      SMTP_PORT: 25
    depends_on:
      - db
      - snmp

