Metric.destroy_all
Metric.create! column_name: 'metric_0', label: 'T extérieure'
Metric.create! column_name: 'metric_1', label: 'TC mes'
Metric.create! column_name: 'metric_2', label: 'TC Ret cons'
Metric.create! column_name: 'metric_3', label: 'Fonct brûleur Std/Imp'
Metric.create! column_name: 'metric_4', label: 'Blocage'
Metric.create! column_name: 'metric_5', label: 'PE1_BR1'
Metric.create! column_name: 'metric_6', label: 'CF1 (Plancher chf) T Dep mes'
Metric.create! column_name: 'metric_7', label: 'CF1 (Plancher chf) T Dep cons'
Metric.create! column_name: 'metric_8', label: 'CF1 (Plancher chf) T Amb mes.'
Metric.create! column_name: 'metric_9', label: 'CF1 (Plancher chf) T Amb Cons'
Metric.create! column_name: 'metric_10', label: 'CF1 (Plancher chf) Pompe'
Metric.create! column_name: 'metric_11', label: 'CF1 (Plancher chf) VanMel'
Metric.create! column_name: 'metric_12', label: 'CF1 (Plancher chf) Etat'
Metric.create! column_name: 'metric_13', label: 'CF2 (Radiateur) T Dep mes'
Metric.create! column_name: 'metric_14', label: 'CF2 (Radiateur) T Dep cons'
Metric.create! column_name: 'metric_15', label: 'CF2 (Radiateur) T Amb mes.'
Metric.create! column_name: 'metric_16', label: 'CF2 (Radiateur) T Amb Cons'
Metric.create! column_name: 'metric_17', label: 'CF2 (Radiateur) Pompe'
Metric.create! column_name: 'metric_18', label: 'CF2 (Radiateur) VanMel'
Metric.create! column_name: 'metric_19', label: 'CF2 (Radiateur) Etat'
Metric.create! column_name: 'metric_20', label: 'Pompe primaire1 Pompe'
Metric.create! column_name: 'metric_21', label: 'PE1 TC mes'
Metric.create! column_name: 'metric_22', label: 'PE1 TC Ret cons'
Metric.create! column_name: 'metric_23', label: 'PE1 T démarrage pompe'
Metric.create! column_name: 'metric_24', label: 'PE1 Niveau de Modulation'
Metric.create! column_name: 'metric_25', label: 'PE1 T Flam mes.'
Metric.create! column_name: 'metric_26', label: 'PE1 T Flam cons.'
Metric.create! column_name: 'metric_27', label: 'PE1 FRT Max'
Metric.create! column_name: 'metric_28', label: 'PE1 t marche vis brûleur'
Metric.create! column_name: 'metric_29', label: 'PE1 temps pause'
Metric.create! column_name: 'metric_30', label: 'PE1 vitesse V comb'
Metric.create! column_name: 'metric_31', label: 'PE1 vitesse V fumées'
Metric.create! column_name: 'metric_32', label: 'PE1 Mesure'
Metric.create! column_name: 'metric_33', label: 'PE1 Consigne'
Metric.create! column_name: 'metric_34', label: 'PE1 Etat'
Metric.create! column_name: 'metric_35', label: 'PE1 Moteur vis brûleur'
Metric.create! column_name: 'metric_36', label: 'PE1 Extraction'
Metric.create! column_name: 'metric_37', label: 'PE1 Moteur réserve 1'
Metric.create! column_name: 'metric_38', label: 'PE1 Turbine'
Metric.create! column_name: 'metric_39', label: 'PE1 Allumeur'
Metric.create! column_name: 'metric_40', label: 'PE1 Pompe chaudière'
Metric.create! column_name: 'metric_41', label: 'PE1 Cendrier'
Metric.create! column_name: 'metric_42', label: 'PE1 Moteur réserve 2'
Metric.create! column_name: 'metric_43', label: 'PE1 Electro-vanne'
Metric.create! column_name: 'metric_44', label: 'PE1 Moteur ramonage'
Metric.create! column_name: 'metric_45', label: 'PE1 Allumeur'
Metric.create! column_name: 'metric_46', label: 'PE1 Kap RA'
Metric.create! column_name: 'metric_47', label: 'PE1 Kap ZW'
Metric.create! column_name: 'metric_48', label: 'PE1 Chaud ex (AK)'
Metric.create! column_name: 'metric_49', label: 'PE1 intervalle aspiration'
Metric.create! column_name: 'metric_50', label: 'PE1 DigIn1'
Metric.create! column_name: 'metric_51', label: 'PE1 DigIn2'
