describe('Home', () => {
  it('displays application name', () => {
      cy.visit('/')
      cy.get('h1')
        .should('contain', 'Monitofen')
      cy.percySnapshot()
  })

  it('display measurements', () => {
        cy.visit('/')
        cy.get('[data-action="explore-measurements"]')
         .click()
        cy.get('[data-type="title"]')
          .should('contain', 'Measurements explorer')
        cy.getByLabel('Day')
          .click()
        const yesterday = Cypress.dayjs().subtract(2, 'day')
        cy.get('[role="menu"]')
          .contains('button', yesterday.date())
          .click();
        cy.getByLabel('Metric')
          .click()
        cy.get('[role="listbox"]')
          .contains('T extérieure')
          .click()
        cy.contains('1438 measurement(s) found')
        cy.get('[data-testid="chart"]')
        cy.percySnapshot()
    })
})